In [1]:
import numpy as np

In [3]:
import numpy as np

In [7]:
a = np.arange(0,12).reshape(3,4)

In [8]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [9]:
a.reshape(a.shape[0], -1)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [12]:
b = np.hsplit(a,2)

In [14]:
b

[array([[0, 1],
        [4, 5],
        [8, 9]]), array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [16]:
c = np.arange(0,16).reshape(2,4,2)

In [20]:
c

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]]])

In [19]:
c.reshape(c.shape[0],-1)

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [21]:
d = np.arange(0,12).reshape(3,2,2)

In [22]:
d

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]]])

In [23]:
d.reshape(d.shape[0],-1)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [26]:
e = np.arange(0,4*3*3*2).reshape(4,3,3,2)

In [27]:
e

array([[[[ 0,  1],
         [ 2,  3],
         [ 4,  5]],

        [[ 6,  7],
         [ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15],
         [16, 17]]],


       [[[18, 19],
         [20, 21],
         [22, 23]],

        [[24, 25],
         [26, 27],
         [28, 29]],

        [[30, 31],
         [32, 33],
         [34, 35]]],


       [[[36, 37],
         [38, 39],
         [40, 41]],

        [[42, 43],
         [44, 45],
         [46, 47]],

        [[48, 49],
         [50, 51],
         [52, 53]]],


       [[[54, 55],
         [56, 57],
         [58, 59]],

        [[60, 61],
         [62, 63],
         [64, 65]],

        [[66, 67],
         [68, 69],
         [70, 71]]]])

In [29]:
f = e.reshape(e.shape[0],-1)

In [30]:
f.shape

(4, 18)

In [32]:
from lr_utils import load_dataset

ModuleNotFoundError: No module named 'lr_utils'

In [36]:
a = np.arange(0,12).reshape(4,3)
b = np.arange(0,4).reshape(4,1)

In [39]:
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [40]:
b

array([[0],
       [1],
       [2],
       [3]])

In [41]:
a*b

array([[ 0,  0,  0],
       [ 3,  4,  5],
       [12, 14, 16],
       [27, 30, 33]])