# TensorFlow

In [1]:
import tensorflow as tf
import numpy as np

Let's start 
>**TensorFlow**

### Tensorflow Constants

There exist only three datatypes
Constant
Placeholder
Variable

In [2]:
x = tf.constant(5) #define tensors
y = tf.constant(6)

z = x + y #Flow

In [3]:
print(z) #just assigns the flow or graph, not yet executed

Tensor("add:0", shape=(), dtype=int32)


In [4]:
with tf.Session() as sess:
    output = sess.run(z) # See that we are assigning run to output
    print(output) # Session closes automatically

11


In [5]:
a = tf.constant(4.0)
b = tf.constant(5.0)

c = a*b

sess = tf.Session()

print(sess.run(c))
sess.close() # In this mode of execution its mandatory to close the session

20.0


In [6]:
node1 = tf.constant(4.0, tf.float32)
node2 = tf.constant(5.0, tf.float16)

sess = tf.Session()
print(sess.run([node1, node2]))
sess.close()

[4.0, 5.0]


### Tensorlfow Placeholder

> A 'placeholder' is a promise to provide a value later

Values fed during execution of sessions

In [7]:
# You can assign tensors during runtime, using feed_dict dictionary
# In below example d is a list of [1,2]
                # e is a list of [3,4]

In [8]:
d = tf.placeholder(tf.float16)
e = tf.placeholder(tf.float16)

f = d * e

sess = tf.Session()

print(sess.run(f, feed_dict = {d:[1,2], e:[3,4]})) #observe the result is elementwise multiplication

sess.close

[3. 8.]


<bound method BaseSession.close of <tensorflow.python.client.session.Session object at 0x000000000AE0F748>>

In [9]:
g = tf.placeholder(tf.float32)
h = tf.placeholder(tf.float32)

adder_node = g + h

sess = tf.Session()
print(sess.run(adder_node, feed_dict = {g:[3,4,5], h:[6,7,8]}))

[ 9. 11. 13.]


In [10]:
Mul_5 = adder_node * 5
print(sess.run(Mul_5, feed_dict = {g:np.random.randint(0, 15, size = (4,4)), 
                                   h:np.random.randint(-14,1, size = (4,4))}))

sess.close()

[[ 45. -40.   0.  10.]
 [ 55.  30. -35.  -5.]
 [-35.  15. -10.  40.]
 [-30.  40. -35. -20.]]


In [11]:
# This means that we can pass different values for placeholder during different run time, 
# and also use previous functions, its independent of the tensors used..... tensor = vector/matrix

### Tensorflow Variables

>Variable allows us to add trainable parameters to the graph

We need an extra command to initialise these variable

In [12]:
W1 = tf.Variable([.5], tf.float16)
#important... need to run below code to execute or inialise the variable
init = tf.global_variables_initializer()

sess = tf.Session()
sess.run(init) #initializes the variable and assigns value 

print(sess.run(W1))

sess.close()

Instructions for updating:
Colocations handled automatically by placer.
[0.5]


In [13]:
#Linear line Y = Wx + b
W = tf.Variable([2.], tf.float32)
b = tf.Variable([1.], tf.float32)
x = tf.placeholder(tf.float32)

Linear_line = W*x + b

init = tf.global_variables_initializer()

sess = tf.Session()
sess.run(init)

print(sess.run(Linear_line, {x:[1,2,3,4]}))


[3. 5. 7. 9.]


To type cast we have tf.cast

In [14]:
print(sess.run(tf.cast(x, tf.int16), {x:[1.,2.,3.,4.]}))

[1 2 3 4]


In [15]:
print(sess.run(tf.cast(Linear_line, tf.int16), {x:[1,2,3,4]}))

[3 5 7 9]


In [16]:
sess.close()

#### Lets Implement Activation function

In [17]:
a = tf.constant([-1, 0, 1., 2., 3., 4.])

sigmoid_activation = tf.sigmoid(a)
tanh_activation = tf.tanh(a)
relu_activation = tf.nn.relu(a)

with tf.Session() as sess:
    output1 = sess.run(sigmoid_activation)
    output2 = sess.run(tanh_activation)
    output3 = sess.run(relu_activation)
    
    print('sigmoid:\t',output1)
    print('tanh:\t', output2)
    print('relu:\t', output3)

sigmoid:	 [0.26894143 0.5        0.7310586  0.8807971  0.95257413 0.98201376]
tanh:	 [-0.7615942  0.         0.7615942  0.9640276  0.9950547  0.9993292]
relu:	 [0. 0. 1. 2. 3. 4.]


###### Truncated normal distribution

```
tf.random.truncated_normal(
    shape,
    mean=0.0,
    stddev=1.0,
    dtype=tf.dtypes.float32,
    seed=None,
    name=None
)```

The generated values follow a normal distribution with specified mean and standard deviation, except that values whose magnitude is more than 2 standard deviations from the mean are dropped and re-picked.

In [18]:
a = tf.truncated_normal([2,3], seed = 1)
with tf.Session() as sess:
    print(sess.run(a))

[[-0.8113182   1.4845988   0.06532937]
 [ 0.0992484   0.6396971   1.6108712 ]]


In [19]:
a = tf.random.truncated_normal([2,3], seed = 1)
with tf.Session() as sess:
    print(sess.run(a))

[[-0.8113182   1.4845988   0.06532937]
 [ 0.0992484   0.6396971   1.6108712 ]]


## Loss Function

- It's measure how far is the current model from given data

In [22]:
W = tf.Variable([.3], tf.float32)
b = tf.Variable([-.3], tf.float32)

x = tf.placeholder(tf.float32)
y = tf.placeholder(tf.float32)

Linear_model = W*x + b

squared_data = tf.square(Linear_model - y)
loss = tf.reduce_sum(squared_data)

init = tf.global_variables_initializer()

sess =tf.Session()
sess.run(init)

print(sess.run(squared_data, {x:[1,2,3,4], y:[0,-1,-2,-3]}))
print(sess.run(loss, {x:[1,2,3,4], y:[0,-1,-2,-3]}))
sess.close()

[ 0.         1.6899998  6.7599993 15.210001 ]
23.66


## Model Optimizer
- modifies each variable according to magnitude of derivative of loss w.r.t that variable

In [25]:
W = tf.Variable([.3], tf.float32)
b = tf.Variable([-.3], tf.float32)

x = tf.placeholder(tf.float32)
y = tf.placeholder(tf.float32)

Linear_model = W*x + b

Square_error = tf.square(Linear_model - y)
loss = tf.reduce_sum(Square_error)

optimizer = tf.train.GradientDescentOptimizer(0.01)
train = optimizer.minimize(loss)

init = tf.global_variables_initializer()

sess = tf.Session()

sess.run(init)

for i in range(3):
    sess.run(train, {x:[1,2,3,4], y:[0,-1,-2,-3]})
    
print(sess.run([W,b]))

[array([-0.459616], dtype=float32), array([-0.4965184], dtype=float32)]
