In [1]:
#refereing to one stackflow answers, trying out snippet to understand how Softmax cross entropy works
import tensorflow as tf
import numpy as np

sess = tf.Session()

In [3]:
#creating one hot version
y_true = tf.convert_to_tensor(np.array([[0.0, 1.0, 0.0], [0.0, 0.0, 1.0]]))

In [4]:
print(sess.run(y_true))

[[0. 1. 0.]
 [0. 0. 1.]]


In [8]:
#random y hat
y_hat = tf.convert_to_tensor(np.random.random((2,3)))

In [9]:
sess.run(y_hat)

array([[0.94975992, 0.2125584 , 0.29806779],
       [0.77383342, 0.68254428, 0.28323388]])

In [10]:
y_hat_softmax = tf.nn.softmax(y_hat)
#this gives class probabilities
print(sess.run(y_hat_softmax))

[[0.50009648 0.23927165 0.26063186]
 [0.39603757 0.36148478 0.24247765]]


In [13]:
#checking maximun value index
sess.run([tf.argmax(y_hat,1), tf.argmax(y_true,1)])

[array([0, 0], dtype=int64), array([1, 2], dtype=int64)]

In [14]:
#this means maximun values are in first position of y_hat and 
#max values are at 2nd and 3rd position of first and second row of y_true

sess.run(tf.equal(tf.argmax(y_hat,1), tf.argmax(y_true,1)))

array([False, False])

In [28]:
temp = tf.cast(tf.equal(tf.argmax(y_hat,1), tf.argmax(y_true,1)), tf.float32)
sess.run(temp)

array([0., 0.], dtype=float32)

In [29]:
sess.run(tf.reduce_mean(temp))

0.0

In [15]:
#to measure loss we need to find cross entropy

$H(p,q) = -\sum(p logq)$

In [16]:
#find loss instance wise
loss_per_instance_1 = -tf.reduce_sum(y_true * tf.log(y_hat_softmax), reduction_indices=[1])
sess.run(loss_per_instance_1)

array([1.43015574, 1.41684574])

In [17]:
#find total loss
total_loss_1 = tf.reduce_mean(-tf.reduce_sum(y_true * tf.log(y_hat_softmax), reduction_indices=[1]))
sess.run(total_loss_1)

1.4235007425713646

## using softmax_cross_entropy_with_logits

In [20]:
loss_per_instance_2 = tf.nn.softmax_cross_entropy_with_logits_v2(logits=y_hat, labels=y_true)
print("loss per instance",sess.run(loss_per_instance_2))

total_loss_2 = tf.reduce_mean(loss_per_instance_2)
print("total loss",sess.run(total_loss_2))

loss per instance [1.43015574 1.41684574]
total loss 1.4235007425713646


# using sparse_softmax_cross_entropy_with_logits

In [ ]:
#creating y_true without one hot version

In [21]:
y_true_no_hot = tf.convert_to_tensor(np.array([1,2]))

In [23]:
sess.run(y_true_no_hot)

array([1, 2])

In [24]:
loss_per_instance_3 = tf.nn.sparse_softmax_cross_entropy_with_logits(logits=y_hat, labels=y_true_no_hot)
print("loss per instance no hot",sess.run(loss_per_instance_3))

total_loss_3 = tf.reduce_mean(loss_per_instance_3)
print("total loss no hot",sess.run(total_loss_2))

loss per instance no hot [1.43015574 1.41684574]
total loss no hot 1.4235007425713646


In [ ]:
# Bingo...!... this is how this works...