In [1]:
import numpy as np

In [10]:
z = ['Hi', 'Today', 'is', 'friday', 'and', 'date', 'is', 12, 'july', 2019]

In [ ]:
# enumerate() gives the position as well as its values

In [11]:
for i in enumerate(z):
    print(i)

(0, 'Hi')
(1, 'Today')
(2, 'is')
(3, 'friday')
(4, 'and')
(5, 'date')
(6, 'is')
(7, 12)
(8, 'july')
(9, 2019)


In [ ]:
# .format() will assign the needed values in needed format in string, specified by location

In [12]:
print("String is {}" .format(z))

String is ['Hi', 'Today', 'is', 'friday', 'and', 'date', 'is', 12, 'july', 2019]


In [13]:
print('Hello {0}, your balance is {1:9}' .format("Adam", 2341.567))

Hello Adam, your balance is  2341.567


In [15]:
print('Hello {0}, your balance is {1:9.2f}' .format("Adam", 2341.567))

Hello Adam, your balance is   2341.57


In [25]:
print("Selected a Strings {0} hence {2} to {1}, test on {3} " .format(z[4], z[0], z[3], z[7:]))

Selected a Strings and hence friday to Hi, test on [12, 'july', 2019] 


In [24]:
print("Selected a Strings {} hence {} to {}, test on {} " .format(z[4], z[0], z[3], z[7:]))

Selected a Strings and hence Hi to friday, test on [12, 'july', 2019] 


In [27]:
import numpy as np

In [28]:
z = np.random.rand(3,3,3)

In [30]:
z[0][0]

array([0.0918235 , 0.70689979, 0.57443111])

In [32]:
z[0][1]

array([0.95523638, 0.49273612, 0.07275759])

In [33]:
z

array([[[0.0918235 , 0.70689979, 0.57443111],
        [0.95523638, 0.49273612, 0.07275759],
        [0.70056719, 0.03188481, 0.49314381]],

       [[0.04142964, 0.10548945, 0.31292806],
        [0.35593237, 0.39329675, 0.53180768],
        [0.02935967, 0.7233095 , 0.07870534]],

       [[0.74939171, 0.75331565, 0.12040093],
        [0.44277005, 0.89213881, 0.52927567],
        [0.77031537, 0.35875962, 0.24116928]]])